repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: ruff
        name: Python ruff
        entry: ruff check
        language: system
        types: [python]
        require_serial: false
