"""Constants for the Ingenium integration."""

DOMAIN = "ingenium"
DEFAULT_NAME = "Ingenium aSC"
ATTR_MANUFACTURER = "Ingenium"
CONF_HOST = "host"
CONF_INSTALLATION_DATA = "installation_data"
CONF_IGNORE_AVAILABILITY = "ignore_availability"
CONF_MAC = "mac"
CONF_VERSION = "version"
TASK_BUSING = "busing"
