name: Validate with test suite

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master

  pytest:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v2.3.4"
      - name: Setup Python 3.12"
        uses: "actions/setup-python@v2.2.1"
        with:
          python-version: "3.12"
      - name: Install requirements
        run: |
          pip install -r requirements_test.txt
      - name: Tests suite
        run: |
          pytest \
            --timeout=9 \
            --durations=10 \
            --cov --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
